### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by Philosoft** [DevGroup-ru/yii2-tag-dependency-helper#4]
- Last commit was 23 days ago;
- there are no open bugs;
- we use this code in production intensively;
- open issues are important but not critical and should be done to date of 1.1 release/milestone (with cool features of #1 and #2 and documentation from #3)

So, my proposal is to push 1.0 tag (reasons listed above), to mark code stability and allow version-specific usage in composer. Also I suggest to stick to [semantic versioning](http://semver.org).

**Comment by bethrezen** [comment]
0.0.2 tag released.
1.0.0 means more wide functions
