### ISSUE TITLE
Add shortcut cache methods

### ISSUE THREAD

**Issue by miramir** [DevGroup-ru/yii2-tag-dependency-helper#5]
``` php
$models = Configurable::getDb()->cache(
    function ($db) {
        return Configurable::find()->all($db);
    },
    86400,
    new TagDependency([
        'tags' => ActiveRecordHelper::getCommonTag(Configurable::className()),
    ])
);
```

may by reduced to:

``` php
$models = Configurable::getDb()->cacheTag(
    function ($db) {
        return Configurable::find()->all($db);
    }
);
```

**Comment by miramir** [comment]
this block

``` php
$cacheKey = 'Product:' . $model_id;
if (false === $product = Yii::$app->cache->get($cacheKey)) {
    if (null === $product = Product::findById($model_id)) {
        throw new NotFoundHttpException;
    }
    Yii::$app->cache->set(
        $cacheKey,
        $product,
        86400,
        new TagDependency(
            [
                'tags' => [
                    ActiveRecordHelper::getObjectTag(Product::className(), $model_id),
                ]
            ]
        )
    );
}
```

reduced to:

``` php
$product = Product::findCachedById($model_id);
```

findCachedById() and findById() also need implemented

**Comment by bethrezen** [comment]
@miramir the last can be made through traits. See this:
https://github.com/DevGroup-ru/dotplant2/blob/2.0.0-beta/application/traits/FindById.php
https://github.com/DevGroup-ru/dotplant2/blob/2.0.0-beta/application/traits/LoadModel.php
https://github.com/DevGroup-ru/dotplant2/blob/2.0.0-beta/application/traits/FindById.php

**Comment by miramir** [comment]
трейты конечно хорошо, но когда эти методы будут реализованы в поведении будет удобнее.

**Comment by bethrezen** [comment]
Traits are faster then behaviors :-)

**Comment by miramir** [comment]
ну тогда их надо поставлять с этим расширением.

**Comment by bethrezen** [comment]
Реализовано в версии 1.2.1
Подробнее:
https://github.com/DevGroup-ru/yii2-tag-dependency-helper#lazy-cache
https://github.com/DevGroup-ru/yii2-tag-dependency-helper#finding-model
